plugins {
    id 'java'
    id 'org.springframework.boot' version "4.1.1"
    id 'io.spring.dependency-management' version "1.1.7"
    id "com.google.protobuf" version "0.10.0"
    id 'com.netflix.dgs.codegen' version '8.6.0'
}

group = 'ru.leti'
version = '2.0.0'
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    // security
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'

    // API
    implementation 'org.springframework.boot:spring-boot-starter-graphql'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-grpc-client'

    // Observability (tracing, metrics, logs)
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-opentelemetry'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'com.github.loki4j:loki-logback-appender:2.1.0'

    // Mapping
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}

sourceSets {
    main {
        proto {
            srcDir 'src/main/resources/proto'
        }
    }
}

generateJava {
    schemaPaths = ["${projectDir}/src/main/resources/graphql"]
    packageName = 'ru.leti.graphql'
    generateClient = true
}

tasks.named('test') {
    useJUnitPlatform()
}
