services:
  wise-task-graph:
    build:
      context: ../wise-task-graph
      dockerfile: Dockerfile
    depends_on:
      - wise-task-mongo
    container_name: wise-task-graph
    ports:
      - "127.0.0.1:${GRAPH_GRPC_PORT}:${GRAPH_GRPC_PORT}"
    environment:
      - MANAGEMENT_METRICS_ENABLE_PROCESS=false
    env_file:
      - .env

  wise-task-plugin:
    build:
      context: ../wise-task-plugin
      dockerfile: Dockerfile
    depends_on:
      - wise-task-db
      - wise-task-task
      - wise-task-graph
    container_name: wise-task-plugin
    ports:
      - "127.0.0.1:${PLUGIN_GRPC_PORT}:${PLUGIN_GRPC_PORT}"
    environment:
      - MANAGEMENT_METRICS_ENABLE_PROCESS=false
    env_file:
      - .env

  wise-task-profile:
    build:
      context: ../wise-task-profile
      dockerfile: Dockerfile
    depends_on:
      - wise-task-db
    container_name: wise-task-profile
    ports:
      - "127.0.0.1:${PROFILE_GRPC_PORT}:${PROFILE_GRPC_PORT}"
    env_file:
      - .env

  wise-task-task:
    build:
      context: ../wise-task-task
      dockerfile: Dockerfile
    depends_on:
      - wise-task-db
      - wise-task-graph
    container_name: wise-task-task
    ports:
      - "127.0.0.1:${TASK_GRPC_PORT}:${TASK_GRPC_PORT}"
    env_file:
      - .env

  wise-task-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - wise-task-profile
      - wise-task-task
      - wise-task-plugin
      - wise-task-graph
    container_name: wise-task-gateway
    ports:
      - "127.0.0.1:${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file:
      - .env
    volumes:
      - ./src/main/resources/application-prod.yaml:/app/config/application-prod.yaml:ro
      - ./src/main/resources/application-dev.yaml:/app/config/application-dev.yaml:ro

  wise-task-event:
    build:
      context: ../wise-task-event
      dockerfile: Dockerfile
    container_name: wise-task-event
    depends_on:
      - wise-task-event-db
    ports:
      - "127.0.0.1:${EVENT_GRPC_PORT}:${EVENT_GRPC_PORT}"
      - "127.0.0.1:${EVENT_PORT}:${EVENT_PORT}"
    environment:
      - MANAGEMENT_METRICS_ENABLE_PROCESS=false
    env_file:
      - .env

  wise-task-event-db:
    image: timescale/timescaledb:2.26.0-pg16
    container_name: ${EVENT_DB_APP_NAME}
    ports:
      - "127.0.0.1:${EVENT_DB_PORT}:${EVENT_DB_PORT}"
    environment:
      POSTGRES_USER: ${EVENT_DB_USER}
      POSTGRES_PASSWORD: ${EVENT_DB_PASSWORD}
      POSTGRES_DB: ${EVENT_DB}
      POSTGRES_PORT: ${EVENT_DB_PORT}
    volumes:
      - wise-task-event-db:/var/lib/postgresql/data
    command: postgres -p ${EVENT_DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wise_task_event -d wise_task_event" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  wise-task-db:
    image: postgres:17-alpine3.22
    container_name: wise-task-db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - wise-task-db:/var/lib/postgresql/data
      - ./docker/postgres/init-scripts:/docker-entrypoint-initdb.d

  wise-task-mongo:
    image: mongo:8.0.4
    container_name: wise-task-mongo
    ports:
      - "127.0.0.1:${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - wise-task-mongo:/data/db

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    container_name: ${TEMPO_HOST}
    volumes:
      - ./docker/tempo/tempo-local.yml:/etc/tempo.yaml
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "127.0.0.1:3200:3200"
      - "127.0.0.1:4318:4318" # http otlp
      - "127.0.0.1:14268:14268" # Jaeger ingest

  loki:
    image: grafana/loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    container_name: ${LOKI_HOST}
    ports:
      - "127.0.0.1:3100:3100"
    environment:
      - JAEGER_AGENT_HOST=${TEMPO_HOST}
      - JAEGER_ENDPOINT=http://${TEMPO_HOST}:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1

  prometheus:
    image: prom/prometheus
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    container_name: ${PROMETHEUS_HOST}
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - loki
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"

  smtp:
    image: boky/postfix
    container_name: ${SMTP_HOST}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${SMTP_PORT}:${SMTP_PORT}"
    environment:
      - SMTP_SERVER_HOSTNAME=${SMTP_HOST}
      - SMTP_SERVER_DOMAIN=${SMTP_DOMAIN}
      - RELAY_NETWORKS=0.0.0.0/0
      - POSTFIX_mailbox_command=/bin/cat
      - ALLOWED_SENDER_DOMAINS=${SMTP_DOMAIN}
      - LOG_TO_STDOUT=1
      - RELAYHOST=[smtp.yandex.ru]:587
      - RELAYHOST_USERNAME=${SMTP_RELAYHOST_USERNAME}
      - RELAYHOST_PASSWORD=${SMTP_RELAYHOST_PASSWORD}
      - POSTFIX_smtp_tls_security_level=encrypt
      - POSTFIX_smtp_sasl_auth_enable=yes
      - POSTFIX_smtp_sasl_password_maps=lmdb:/etc/postfix/sasl_passwd
      - POSTFIX_smtp_sasl_security_options=noanonymous
    hostname: ${SMTP_HOST}

  grafana:
    image: grafana/grafana
    volumes:
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/dashboards:/etc/grafana/dashboards
      - ./docker/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_BASIC_ENABLED="false"
      - GF_AUTH_DISABLE_LOGIN_FORM="true"
      - GF_AUTH_DISABLE_SIGNOUT_MENU="true"
      - GF_AUTH_PROXY_ENABLED="true"
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - tempo
      - loki
      - prometheus
    ports:
      - "127.0.0.1:3000:3000"

volumes:
  wise-task-mongo: {}
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  druid_shared: {}
  wise-task-db: {}
  wise-task-event-db: {}
