server:
  http_listen_port: 3200
  http_listen_address: 0.0.0.0

distributor:
  receivers:
    zipkin:
      endpoint: 0.0.0.0:9411
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318


storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo